### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by icemac** [zopefoundation/RestrictedPython#224]
Look through the change log of Python 3.11 (once the final version is released) for potential issues which need to be handled by RestrictedPython to prevent access to otherwise forbidden data/objects.

There is no need to support new language features of Python 3.11 right now, let's see how they evolve when started being used.

Open tasks:

- [X] make package installable and fix tests (#223)
- [X] cut an alpha dev release (5.3a1.dev0)
- [x] drop Python 2 support (and Python 3.5) for a sane Python 3.11 support (See #223 for details)
- [ ] look through the change log of the final Python 3.11.0 version for potential changes allowing to bypass restrictions #243

**Comment by loechel** [comment]
@icemac why keep Python 3.6 support? It is already End of life (https://devguide.python.org/versions/)  

I am at the PloneConf and would like to make RestrictedPython 6.0 ready for shipping / maybe a release-candidate package on pypi so that the others could check and test Plone for Python 3.11 support. 
I guess everything should be in the master branch? I did have a look and do not see all Python 2 support dropped there. 

Any suggestions what to do and look at?

**Comment by icemac** [comment]
@loechel We already have a dev release at https://pypi.org/project/RestrictedPython/6.0a1.dev0/ to test against Python 3.11. (Zope 5.dev is already using that version on Python 3.11.)

I decided to keep Python 3.6 support like it is the current policy for zopefoundation projects dropping Python 2.7 and 3.5 support. Plus keeping it makes no harm.

If you found Python 2 support code: Please create a PR to remove it.
